### ISSUE TITLE
Few typos under 2)

### ISSUE THREAD

**Issue by CharlesARoy** [biom262/cmm262-2020#3]
This is for the Module 0 homework instructions and probably falls under extra credit option 1 (fixing of typos which lead to ... confusing wording). 

This might be mac-version-specific, but for me, after entering:
`ssh-keygen -t rsa`
I didn't have to press enter, then it asked me where the file was being stored, and then it asked for the passphrase. So slightly different order than as stated in 2), though these differences are pretty trivial.

**Comment by ckmah** [comment]
Thanks for the detailed notes @CharlesARoy! Can you make a pull request with the changes you just described? DM me for details 😄

**Comment by danielanach** [comment]
Addressed in pull request #9
